language: python
python:
  - 3.7

env:
  jobs:
    - PYGAME_VERSION=1.9.6
    - PYGAME_VERSION=2.0.0.dev6
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
      sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev \
        libsdl-ttf2.0-dev libsdl1.2-dev python-numpy libportmidi-dev libjpeg-dev \
        libtiff5-dev libx11-6 libx11-dev xfonts-base xfonts-100dpi xfonts-75dpi \
        xfonts-cyrillic fluid-soundfont-gm musescore-soundfont-gm \
        libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
    fi
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install -q pygame==$PYGAME_VERSION
  - python setup.py -q install

script: pytest --cov-report=xml --cov=pygame_gui tests/

after_success:
    - codecov