language: python
python:
  - 3.8

install: python setup.py install

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

script: pytest --cov-report term --cov=pygame_gui

after_success:
    - codecov