language: python
sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      python: 3.7
      env: PYGAME_VERSION=2.0.0.dev6
    - os: windows
      language: sh
      before_install:
        - git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$PATH"
        - pyenv install -q 3.7.1
        - pyenv rehash
        - pyenv local 3.7.1
        - python --version
        - pip install pytest
        - pip install pytest-cov
        - pip install codecov
        - pip install -q pygame==2.0.0.dev6
        - python setup.py -q install
    - os: linux
      python: 3.5
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.5
      env: PYGAME_VERSION=2.0.0.dev6
    - os: linux
      python: 3.6
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.6
      env: PYGAME_VERSION=2.0.0.dev6
    - os: linux
      python: 3.7
      env: PYGAME_VERSION=1.9.6
    - os: linux
      python: 3.7
      env: PYGAME_VERSION=2.0.0.dev6
    # No Travis version of 1.9.6 on Python 3.8 yet
    - os: linux
      python: 3.8
      env: PYGAME_VERSION=2.0.0.dev6


install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install -q pygame==$PYGAME_VERSION
  - python setup.py -q install

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

script: pytest --cov-report=xml --cov=pygame_gui tests/

after_success:
    - codecov