language: python
python:
  - 3.8

install: python setup.py install

env:
  - CODECOV_TOKEN="d34c6710-eed9-42ff-b9cd-15b0f18fefe2"
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

script: py.test --cov-report term --cov=pygame_gui
